#!/bin/bash
set -e

case "$1" in
    configure)

export ADITAS_LOAD_PATH="/etc/aditas/agent/scripts/shell/load_paths.sh"
if [ -f "${ADITAS_LOAD_PATH}" ]; then
. "${ADITAS_LOAD_PATH}"
fi
. /usr/share/debconf/confmodule

if [ -f "${ADITAS_DBCONF_VALUES}" ]; then
. "${ADITAS_DBCONF_VALUES}"
fi

if [ -f "${ADITAS_INSTALLER_SCRIPT}" ];then

. "${ADITAS_INSTALLER_SCRIPT}" "install"

fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
